// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANj45Jc4E8Xgoi6jWJDM03inNMxRp0Cos',
    appId: '1:386391610935:web:24e3d49cde31e2273b91b2',
    messagingSenderId: '386391610935',
    projectId: 'chatapp-zainafxal',
    authDomain: 'chatapp-zainafxal.firebaseapp.com',
    storageBucket: 'chatapp-zainafxal.appspot.com',
    measurementId: 'G-MHXTQN7LN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFEOMWiIXpUAV4Xo-pp0PjBKAVlOpXpE',
    appId: '1:386391610935:android:d175a62863c73b553b91b2',
    messagingSenderId: '386391610935',
    projectId: 'chatapp-zainafxal',
    storageBucket: 'chatapp-zainafxal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEb_WHC0WrFAXM5ykPDoE1EjAHYQsgKjI',
    appId: '1:386391610935:ios:b0ccb11ae23db2963b91b2',
    messagingSenderId: '386391610935',
    projectId: 'chatapp-zainafxal',
    storageBucket: 'chatapp-zainafxal.appspot.com',
    iosBundleId: 'com.zainafxal.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEb_WHC0WrFAXM5ykPDoE1EjAHYQsgKjI',
    appId: '1:386391610935:ios:b0ccb11ae23db2963b91b2',
    messagingSenderId: '386391610935',
    projectId: 'chatapp-zainafxal',
    storageBucket: 'chatapp-zainafxal.appspot.com',
    iosBundleId: 'com.zainafxal.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANj45Jc4E8Xgoi6jWJDM03inNMxRp0Cos',
    appId: '1:386391610935:web:85fd854cd094e8963b91b2',
    messagingSenderId: '386391610935',
    projectId: 'chatapp-zainafxal',
    authDomain: 'chatapp-zainafxal.firebaseapp.com',
    storageBucket: 'chatapp-zainafxal.appspot.com',
    measurementId: 'G-0X8Y9CM4YE',
  );
}
